---
-  hosts: all
   become: true
   vars:
      docker_image_name: rameshk9059/to-do-app
      docker_image_tag: latest
   tasks:

      - name: copy the code from jenkins to docker server
        synchronize:
           src: ../
           dest: /opt/to-do-app
           recursive: yes


      - name: Log in to Docker Hub
        docker_login:
           username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
           password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

      - name: Build the docker image
        docker_image:
            name: "{{ docker_image_name }}"
            tag: "{{ docker_image_tag }}"

            build:
              path: /opt/to-do-app/backend

      - name: Run Docker container
        docker_container:
         name: to-do-container
         image: "{{ docker_image_name }}:{{ docker_image_tag }}"
         state: started
         restart_policy: always
         ports:
            - "80:4000"
               
