---
- name: Build and push the docker image
  hosts: all
  become: true
  vars:
    repo_url: https://github.com/rameshk9059/to-do-app.git
    image_name: rameshk9059/todo:latest
  tasks:
    - name: ensure git installed
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: /tmp/to-do-app
        force: yes

    - name: Docker build
      command: docker build -t {{ image_name }} .
      args:
        chdir: /tmp/to-do-app/backend

    - name: Login to Docker Hub
      shell: echo "{{ dockerhub_password }}" | docker login -u "{{ dockerhub_username
        }}" --password-stdin
      no_log: true

    - name: Push the Docker image
      command: docker push {{ image_name }}

    - name: Docker build
      command: docker build -t {{ image_name }} .
      args:
        chdir: /tmp/to-do-app/backend

    - name: Create directory for Trivy report
      file:
        path: /tmp/trivy_scan
        state: directory
        mode: '0755'

    - name: Scan the image with trivy
      command: trivy image -f json -o /tmp/trivy_scan/report.json {{ image_name }}

    - name: Docker container creation
      command: docker run -dit -p 4000:4000 --name todo-app {{ image_name }}
