name: Update Badges in README

on:
  push:
    paths:
      - Badges.md
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse Badges.md and update README.md badges
        run: |
          # Function to pick badge color by value
          get_color() {
            val=$1
            if [ "$val" -lt 50 ]; then
              echo "red"
            elif [ "$val" -lt 75 ]; then
              echo "yellow"
            elif [ "$val" -lt 90 ]; then
              echo "blue"
            else
              echo "brightgreen"
            fi
          }

          # Parse Badges.md to extract sections and values
          awk '
          BEGIN { section=""; }
          /^Input:/ {
            section = $2;
            getline; video = $2;
            getline; audio = $2;

            gsub("%", "", video);
            gsub("%", "", audio);

            print section, video, audio;
          }' Badges.md > parsed.txt

          # Backup README.md before modifying
          cp README.md README.md.bak

          while read section video audio; do
            video_color=$(get_color $video)
            audio_color=$(get_color $audio)

            video_badge="![Video Accuracy](https://img.shields.io/badge/Video_Accuracy-${video}%%25-${video_color})"
            audio_badge="![Audio Accuracy](https://img.shields.io/badge/Audio_Accuracy-${audio}%%25-${audio_color})"

            marker=$(echo "$section" | tr '[:lower:]' '[:upper:]')

            echo "Updating badges for section: $section"

            # Show current badge block before update
            echo "Before update:"
            sed -n "/<!-- BADGES_${marker}_START -->/,/<!-- BADGES_${marker}_END -->/p" README.md

            # Replace badges between markers
            awk -v head="<!-- BADGES_${marker}_START -->" \
                -v tail="<!-- BADGES_${marker}_END -->" \
                -v badge="${video_badge} ${audio_badge}" '
              $0 == head { print; print badge; inblock=1; next }
              $0 == tail { inblock=0; print; next }
              !inblock { print }
            ' README.md > README.tmp && mv README.tmp README.md

            # Show badge block after update
            echo "After update:"
            sed -n "/<!-- BADGES_${marker}_START -->/,/<!-- BADGES_${marker}_END -->/p" README.md
          done < parsed.txt

      - name: Commit and push changes
        run: |
          git config user.name "ramesh-github-actions"
          git config user.email "github-actions@github.com"
          git add README.md

          if ! git diff --cached --quiet; then
            git commit -m "[skip ci] Update badges from Badges.md"
            
            # Pull remote changes and rebase to avoid conflicts
            git pull --rebase origin main

            # Push after rebase
            git push origin main
          else
            echo "No changes detected, skipping commit."
          fi

